//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ackShufflerMessage.msg.
//

#ifndef __ACKSHUFFLERMESSAGE_M_H
#define __ACKSHUFFLERMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ackShufflerMessage;
/**
 * Class generated from <tt>ackShufflerMessage.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message ackShufflerMessage
 * {
 *     string nodeSent; //operazione da fare
 *     string partitionSent; //partizione da cui leggere
 * 
 * }
 * </pre>
 */
class ackShufflerMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string nodeSent;
    omnetpp::opp_string partitionSent;

  private:
    void copy(const ackShufflerMessage& other);

  protected:
    bool operator==(const ackShufflerMessage&) = delete;

  public:
    ackShufflerMessage(const char *name=nullptr, short kind=0);
    ackShufflerMessage(const ackShufflerMessage& other);
    virtual ~ackShufflerMessage();
    ackShufflerMessage& operator=(const ackShufflerMessage& other);
    virtual ackShufflerMessage *dup() const override {return new ackShufflerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getNodeSent() const;
    virtual void setNodeSent(const char * nodeSent);

    virtual const char * getPartitionSent() const;
    virtual void setPartitionSent(const char * partitionSent);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ackShufflerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ackShufflerMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ackShufflerMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<ackShufflerMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ACKSHUFFLERMESSAGE_M_H

