//
// Generated file, do not edit! Created by opp_msgtool 6.0 from OperationMessage.msg.
//

#ifndef __OPERATIONMESSAGE_M_H
#define __OPERATIONMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class OperationMessage;
/**
 * Class generated from <tt>OperationMessage.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message OperationMessage
 * {
 *     string operationToDo; //operazione da fare
 *     string partitionToRead; //partizione da cui leggere
 *     int nodeToSend;
 * }
 * </pre>
 */
class OperationMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string operationToDo;
    omnetpp::opp_string partitionToRead;
    int nodeToSend = 0;

  private:
    void copy(const OperationMessage& other);

  protected:
    bool operator==(const OperationMessage&) = delete;

  public:
    OperationMessage(const char *name=nullptr, short kind=0);
    OperationMessage(const OperationMessage& other);
    virtual ~OperationMessage();
    OperationMessage& operator=(const OperationMessage& other);
    virtual OperationMessage *dup() const override {return new OperationMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getOperationToDo() const;
    virtual void setOperationToDo(const char * operationToDo);

    virtual const char * getPartitionToRead() const;
    virtual void setPartitionToRead(const char * partitionToRead);

    virtual int getNodeToSend() const;
    virtual void setNodeToSend(int nodeToSend);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OperationMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OperationMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline OperationMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<OperationMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __OPERATIONMESSAGE_M_H

