//
// Generated file, do not edit! Created by opp_msgtool 6.0 from reducerAckCoordinatorMessage.msg.
//

#ifndef __REDUCERACKCOORDINATORMESSAGE_M_H
#define __REDUCERACKCOORDINATORMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class reducerAckCoordinatorMessage;
/**
 * Class generated from <tt>reducerAckCoordinatorMessage.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * message reducerAckCoordinatorMessage
 * {
 *     int reducerSender; //operazione da fare
 *     string partitionReduced; //partizione da cui leggere
 * 
 * }
 * </pre>
 */
class reducerAckCoordinatorMessage : public ::omnetpp::cMessage
{
  protected:
    int reducerSender = 0;
    omnetpp::opp_string partitionReduced;

  private:
    void copy(const reducerAckCoordinatorMessage& other);

  protected:
    bool operator==(const reducerAckCoordinatorMessage&) = delete;

  public:
    reducerAckCoordinatorMessage(const char *name=nullptr, short kind=0);
    reducerAckCoordinatorMessage(const reducerAckCoordinatorMessage& other);
    virtual ~reducerAckCoordinatorMessage();
    reducerAckCoordinatorMessage& operator=(const reducerAckCoordinatorMessage& other);
    virtual reducerAckCoordinatorMessage *dup() const override {return new reducerAckCoordinatorMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getReducerSender() const;
    virtual void setReducerSender(int reducerSender);

    virtual const char * getPartitionReduced() const;
    virtual void setPartitionReduced(const char * partitionReduced);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const reducerAckCoordinatorMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, reducerAckCoordinatorMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline reducerAckCoordinatorMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<reducerAckCoordinatorMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __REDUCERACKCOORDINATORMESSAGE_M_H

